import edu.rit.ds.RemoteEvent;

/**
 * Class NodeEvent encapsulates a remote event generated by a node in the
 * P2Pedia system. The node events are used to report query activity to the log
 * programs.
 */
public class GPSOfficeEvent
   extends RemoteEvent
   {
   public final String nodeID;
   public final String message;
  public final long TrackNo;
  public String nexthop;
   /**
    * Create a new node event.
    *
    * @param  nodeID  ID of node that received a query.
    * @param  query   Query that was received.
    */
   public GPSOfficeEvent
      (String nodeID,
       String message,
       long TracNo,String nexthop)
      {
      this.nodeID = nodeID;
      this.message = message;
      this.TrackNo=TracNo;
      this.nexthop=nexthop;
     
      }
   }